### PR TITLE
[Fixes #30] Ensure threads are not left hanging, if the request times out

### LINKED ISSUE #30: Timeouts leave threads hanging
I believe I've come across an issue when running requests in many threads (one thread per request) and some (but not all) of them time out.

The timeouts seem to be "honored" but the thread that initiated the request is left waiting for a semaphore: doing some debugging in Xcode's thread view, I noticed all the threads were stuck on [this line](https://github.com/JustHTTP/Just/blob/master/Just/Just.swift#L904):
```
dispatch_semaphore_wait(semaphore, DISPATCH_TIME_FOREVER)
```
when I changed it to something like:
```
                        let NSEC: Int64 = {
                            var base: Int64 = 1
                            for _ in 1...9 {
                                base *= 10
                            }
                            return base
                        }()

                        let tint: Int64 = Int64(timeout ?? 10.0)
                        let how_long = dispatch_time(DISPATCH_TIME_NOW, tint * NSEC)

                        dispatch_semaphore_wait(semaphore, how_long)
```
my code now runs without problem, I can see threads being created then destroyed, and it's now been running for > 1 hour without any issue (it used to just crash and die with a hundred or so of hung threads in a couple of minutes).

If you want, I'd be happy to polish the fix and push a PR?

### PR DESCRIPTION
**Pull request by massenz**
Sorry for jumping the gun, but we are in a bit of a hurry to get the app out for testing and this is a blocker for us.

Happy to make whatever changes deemed necessary to the patch; in particular, I'm not sure anything should be done in case of timeouts, maybe return `nil` instead of the response?

### CODE REVIEW

File: Just/Just.swift [hunk 1]
```diff
@@ -901,7 +901,20 @@ public final class HTTP: NSObject, NSURLSessionDelegate, JustAdaptor {
                         task.resume()
                     }
                     if isSync {
-                        dispatch_semaphore_wait(semaphore, DISPATCH_TIME_FOREVER)
+                        // Express one second in nanoseconds.
+                        let NSEC: Int64 = 1000000000
```
Comment (dduan) [inline Just/Just.swift]: You can use the system constant `NSEC_PER_SEC`.

File: Just/Just.swift [hunk 2]
```diff
@@ -901,7 +901,20 @@ public final class HTTP: NSObject, NSURLSessionDelegate, JustAdaptor {
...
+
+                        if let tint = timeout {
```
Comment (dduan) [inline Just/Just.swift]: `tint` doesn't make much sense. Perhaps mask the old variable aka `if let timeout = timeout`?

File: Just/Just.swift [hunk 3]
```diff
@@ -901,7 +901,20 @@ public final class HTTP: NSObject, NSURLSessionDelegate, JustAdaptor {
...
+                            // See Issue #30 for an explanation of why this is needed.
+                            let how_long = dispatch_time(DISPATCH_TIME_NOW, Int64(tint) * NSEC)
+                            let timed_out = dispatch_semaphore_wait(semaphore, how_long)
+                            if timed_out != 0 {
```
Comment (dduan) [inline Just/Just.swift]: We can ignore the error code for now.

File: Just/Just.swift [hunk 4]
```diff
@@ -901,7 +901,20 @@ public final class HTTP: NSObject, NSURLSessionDelegate, JustAdaptor {
                         task.resume()
                     }
                     if isSync {
-                        dispatch_semaphore_wait(semaphore, DISPATCH_TIME_FOREVER)
+                        // Express one second in nanoseconds.
+                        let NSEC: Int64 = 1000000000
+
+                        if let tint = timeout {
+                            // See Issue #30 for an explanation of why this is needed.
+                            let how_long = dispatch_time(DISPATCH_TIME_NOW, Int64(tint) * NSEC)
```
Comment (dduan) [inline Just/Just.swift]: Can you change the variable names to `howLong` and `timedOut` for consistency?

**Comment by dduan** [comment]
Overall LGTM. Please make the stylistic changes. I'll merge and make a new release right away.

File: Just/Just.swift (hunk 1 above)
Comment (massenz) [inline Just/Just.swift]: Thanks - I have actually figured out that this won't work (as intended) because converting *before* multiplying causes loss of precision.
`NSEC_PER_SEC` is a `UInt64` too, so would have the same problem.
Changed my code to:
```
let timeoutNanosecs: Int64 = Int64(tint * 1000000000.0)
```
Not great, admittedly, but given that Swift isn't smart enough to allow a multiplication between an `Int64` and a `Double`, I'm afraid we're stuck with this?
(I have only coded in Swift for less than 3 weeks - so very happy to get suggestions here!)

File: Just/Just.swift (hunk 2 above)
Comment (massenz) [inline Just/Just.swift]: <facepalm> done.

File: Just/Just.swift (hunk 4 above)
Comment (massenz) [inline Just/Just.swift]: yes - sorry, `dispatch_semaphore...` and all that jazz, got me distracted!

**Comment by massenz** [comment]
Thanks for super-quick review!
Made all the changes.

**Comment by dduan** [comment]
Very cool, thank you!

**Comment by massenz** [comment]
@dduan - thank *you*!
Really appreciate your being so responsive.
